'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { store } from './store'
import { Provider } from 'react-redux'
import { Toaster } from 'react-hot-toast'
import Initializer from '@/components/Initializer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rent Car App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Initializer />
          <div>
            <Toaster />
          </div>
          {children}
        </Provider>
      </body>
    </html>
  )
}
